name: PHP Code Sniffer

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    paths:
      - 'src/**.php'
      - '*.php'

jobs:
  phpcs:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Auto Correct PHP Code Standards Violations
        id: phpcbf
        run: composer run-script phpcbf
        continue-on-error: true

#      - name: Dump phpcbf step context
#        env:
#          STEPS_CONTEXT: ${{ toJson(steps) }}
#        run: echo "$STEPS_CONTEXT"
#
#      - name: Check on failures for phpcbf
#        if: steps.phpcbf.outputs.status > 1
#        run: exit 1

      - name: Detecting PHP Code Standards Violations
        run: composer run-script phpcs
