name: PHP Code Sniffer

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    paths:
      - 'src/**.php'
      - '*.php'

jobs:
  phpcs:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Auto Correct PHP Code Standards Violations
        id: phpcbf
        run: composer run-script phpcbf
        continue-on-error: true
        # Exit code 0 is used to indicate that no fixable errors were found, and so nothing was fixed
        # Exit code 1 is used to indicate that all fixable errors were fixed correctly
        # Exit code 2 is used to indicate that PHPCBF failed to fix some of the fixable errors it found
        # Exit code 3 is used for general script execution errors

      - name: Detecting PHP Code Standards Violations
        run: composer run-script phpcs

      - name: GIT add-push corrected code
        run: |
          git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
          git pull github ${GITHUB_REF} --ff-only
          git config user.name "Maykonn"
          git config user.email "maykonn@outlook.com"
          git commit -am "PHP_CodeSniffer -> code standards were applied on the CI process"

      - name: GIT push the corrected code
        run: git push github HEAD:${GITHUB_REF}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
